export const APP_CONFIGS = {
  accidents: {
    id: 'accidents',
    title: '交通事故発生マップ',
    eyebrow: '山城ヤサカ交通 安全管理',
    sourceName: '事故データ',
    listTitle: '事故一覧',
    mapLabel: '事故発生地点の地図',
    searchPlaceholder: '場所・損傷部位・原因概要',
    summaryLabels: {
      total: '表示件数',
      topCategory: '最多カテゴリ',
      topTimeBand: '最多時間帯',
      topLocation: '重点場所',
    },
    filterLabels: {
      type: '事故区分',
      category: 'カテゴリ',
    },
    tableLabels: {
      date: '発生日',
      time: '時間',
      location: '場所',
      type: '事故区分',
      category: 'カテゴリ',
      detail: '損傷部位',
      cause: '原因概要',
    },
    stats: {
      time: '時間帯別',
      category: 'カテゴリ別',
      location: '場所別',
      prevention: '再発防止ポイント',
    },
    generatedPoints: {
      '後退時接触': '後退開始前の降車確認、誘導者確認、バックモニター確認を標準動作として再点検する。',
      '追突': '車間距離と速度管理を朝礼で確認し、前方不注意が起きやすい時間帯を共有する。',
      '歩行者接触': '横断歩道・乗降場所付近では徐行と左右確認を徹底し、死角確認の声かけを行う。',
      '物損': '狭路・駐車場では一時停止、ミラー確認、切り返し判断を早める。',
    },
  },
  violations: {
    id: 'violations',
    title: '交通違反マップ',
    eyebrow: '山城ヤサカ交通 コンプライアンス確認',
    sourceName: '違反データ',
    listTitle: '違反一覧',
    mapLabel: '交通違反発生地点の地図',
    searchPlaceholder: '場所・対象・違反概要',
    summaryLabels: {
      total: '表示件数',
      topCategory: '最多違反',
      topTimeBand: '最多時間帯',
      topLocation: '重点場所',
    },
    filterLabels: {
      type: '違反区分',
      category: '違反カテゴリ',
    },
    tableLabels: {
      date: '確認日',
      time: '時間',
      location: '場所',
      type: '違反区分',
      category: '違反カテゴリ',
      detail: '対象',
      cause: '違反概要',
    },
    stats: {
      time: '時間帯別',
      category: '違反カテゴリ別',
      location: '場所別',
      prevention: '改善ポイント',
    },
    generatedPoints: {
      '一時停止不履行': '一時停止線の手前で完全停止し、左右確認を声出しで徹底する。',
      '速度超過': '速度が上がりやすい区間を点呼で共有し、法定速度と社内基準速度を再確認する。',
      '進入禁止': '標識確認が必要な交差点を地図で共有し、進入前の標識確認を習慣化する。',
      'ながら運転': '運転中の端末操作を禁止し、連絡は安全な停車後に行う。',
    },
  },
  enforcement: {
    id: 'enforcement',
    title: '取り締まり情報マップ',
    eyebrow: '山城ヤサカ交通 運行注意情報',
    sourceName: '取り締まり情報',
    listTitle: '取り締まり情報一覧',
    mapLabel: '取り締まり地点の地図',
    searchPlaceholder: '場所・対象・注意概要',
    summaryLabels: {
      total: '表示件数',
      topCategory: '最多種別',
      topTimeBand: '多い時間帯',
      topLocation: '注意場所',
    },
    filterLabels: {
      type: '取り締まり区分',
      category: '種別',
    },
    tableLabels: {
      date: '確認日',
      time: '時間',
      location: '場所',
      type: '取り締まり区分',
      category: '種別',
      detail: '対象',
      cause: '注意概要',
    },
    stats: {
      time: '時間帯別',
      category: '種別別',
      location: '場所別',
      prevention: '運行注意ポイント',
    },
    generatedPoints: {
      '速度取締': '速度確認区間では早めに減速し、周囲の流れに流されない運転を徹底する。',
      '一時停止': '見通しのよい交差点でも停止線手前で完全停止し、左右確認を省略しない。',
      '携帯電話': '停車中を含め、端末操作の可否を社内ルールに沿って確認する。',
      'シートベルト': '出庫前と乗務交代時に着用確認を行う。',
    },
  },
  pickups: {
    id: 'pickups',
    title: 'お客様の乗車位置マップ',
    eyebrow: '山城ヤサカ交通 乗車需要分析',
    sourceName: '乗車位置データ',
    listTitle: '乗車位置一覧',
    mapLabel: 'お客様の乗車位置の地図',
    searchPlaceholder: '場所・乗車ポイント・概要',
    summaryLabels: {
      total: '表示件数',
      topCategory: '最多種別',
      topTimeBand: '多い時間帯',
      topLocation: '重点乗車場所',
    },
    filterLabels: {
      type: '乗車区分',
      category: '種別',
    },
    tableLabels: {
      date: '確認日',
      time: '時間',
      location: '乗車場所',
      type: '乗車区分',
      category: '種別',
      detail: '乗車ポイント',
      cause: '概要',
    },
    stats: {
      time: '時間帯別',
      category: '種別別',
      location: '乗車場所別',
      prevention: '配車・待機ポイント',
    },
    generatedPoints: {
      'ヤサカ無線': '無線配車が多い場所は、建物入口や待ち合わせ位置を乗務員間で共有する。',
      'GOアプリ': 'アプリ配車が集中する地点は、迎車しやすい停車位置を整理する。',
      'DiDi': 'DiDi配車が多い地点は、迎車動線と停車しやすい場所を確認する。',
    },
  },
};

export function getCurrentAppConfig() {
  return APP_CONFIGS[document.body.dataset.app] ?? APP_CONFIGS.accidents;
}
